import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import Providers from "../providers";
import "../globals.css";
import { NavbarSection } from "../components/Navbar";

const vazir = Vazirmatn({ subsets: ["latin", "arabic", "latin-ext"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={vazir.className}>
        <Providers>
          <NavbarSection />
          {children}
        </Providers>
      </body>
    </html>
  );
}
