import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import Providers from "../providers";
import "../globals.css";
import { NavbarSection } from "../components/Navbar";
import { Suspense } from "react";
import LoadingLayout from "./loading";
import { FooterSection } from "../components/Footer";

const vazir = Vazirmatn({ subsets: ["latin", "arabic", "latin-ext"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body
        className={`${vazir.className} bg-white dark:bg-black text-onWhite dark:text-onBlack lg:px-10 xl:px-28 2xl:px-80`}
      >
        <Providers>
          <Suspense fallback={<LoadingLayout />}>
            <NavbarSection />
            {children}
            <FooterSection />
          </Suspense>
        </Providers>
      </body>
    </html>
  );
}
